version: "3"
services:
    app:
        image: laravel-www
        container_name: app
        build:
            context: .
            dockerfile: Dockerfile
        depends_on:
            - db
        ports:
            - "8080:80"
        volumes:
            - .:/var/www/html
        environment:
            APP_ENV: local
            CONTAINER_ROLE: app

    db:
        container_name: db
        platform: linux/amd64
        image: mysql
        ports:
            - "3308:3306"
        volumes:
            - dbdata:/var/lib/mysql/
        environment:
            MYSQL_DATABASE: laravel
            MYSQL_ROOT_PASSWORD: root
            MYSQL_USER: homestead
            MYSQL_PASSWORD: secret
    scheduler:
        image: laravel-www
        container_name: scheduler
        depends_on:
            - app
            - db
        volumes:
            - .:/var/www/html
        environment:
            APP_ENV: local
            CONTAINER_ROLE: scheduler

volumes:
    dbdata:
        driver: local
