version: "3"
services:
    urlapp:
        image: laravel-www
        container_name: urlapp
        build:
            context: .
            dockerfile: Dockerfile
        depends_on:
            - urlmysql
        ports:
            - "8080:80"
        volumes:
            - .:/var/www/html
        environment:
            APP_ENV: local
            CONTAINER_ROLE: app

    urlmysql:
        container_name: urlmysql
        platform: linux/amd64
        image: mysql
        ports:
            - "3308:3306"
        volumes:
            - dbdata:/var/lib/mysql/
        environment:
            MYSQL_DATABASE: laravel
            MYSQL_ROOT_PASSWORD: root
            MYSQL_USER: homestead
            MYSQL_PASSWORD: secret
    queue:
        image: laravel-www
        container_name: laravel-queue
        depends_on:
            - urlapp
        volumes:
            - .:/var/www/html
        environment:
            APP_ENV: local
            CONTAINER_ROLE: queue

volumes:
    dbdata:
        driver: local
